export const WINDOWS_RESIZED = 'WINDOWS_RESIZED';
export const TOGGLE_SIDEBAR_COLLAPSED = 'TOGGLE_SIDEBAR_COLLAPSED';
export const SET_NAV_STYLE = 'SET_NAV_STYLE';
export const SET_CURRENT_MENU = 'SET_CURRENT_MENU';
