export const FORGOT_PASSWORD_REQUESTED = 'FORGOT_PASSWORD_REQUESTED';
export const FORGOT_PASSWORD_SUCCEEDED = 'FORGOT_PASSWORD_SUCCEEDED';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';

export const FORGOT_PASSWORD_PAGE_ENTER = 'FORGOT_PASSWORD_PAGE_ENTER';
export const FORGOT_PASSWORD_PAGE_LEAVE = 'FORGOT_PASSWORD_PAGE_LEAVE';
