import { SET_CURRENT_MENU, SET_NAV_STYLE, TOGGLE_SIDEBAR_COLLAPSED, WINDOWS_RESIZED } from '../modules/appUI/store/types';

export { WINDOWS_RESIZED, TOGGLE_SIDEBAR_COLLAPSED, SET_NAV_STYLE, SET_CURRENT_MENU };
